add sonar config

diff --git a/.github/workflows/ci-backend.yml b/.github/workflows/ci-backend.yml
--- a/.github/workflows/ci-backend.yml
+++ b/.github/workflows/ci-backend.yml
@@ -64,3 +64,37 @@ jobs:
             -Dsonar.projectKey=MickC0_FS-P10-Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
             -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
             -Dproject.settings=../sonar-backend.properties
+
+      - name: SonarQube Scan on pull request
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          mvn clean install sonar:sonar -X \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.organization=MickC0 \
+            -Dsonar.projectKey=MickC0_FS-P10-Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
+            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
+            -Dproject.settings=../sonar-backend.properties \
+            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
+            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
+            -Dsonar.pullrequest.base=${{ github.base_ref }}
+
+      - name: SonarQube Quality Gate Check
+        id: quality-gate
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        with:
+          scanMetadataReportFile: back/target/sonar/report-task.txt
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        continue-on-error: true
+
+      - name: Check requirements
+        if: ${{ steps.run-backend-tests.outcome == 'failure' || steps.quality-gate.outcome == 'failure'}}
+        run: |
+          echo "Job failed :"
+          if [ "${{ steps.run-backend-tests.outcome }}" == "failure" ]; then
+            echo "Coverage checks have not been met. See step 'Run tests and generate coverage report' output, and coverage report"
+          fi
+          if [ "${{ steps.quality-gate.outcome }}" == "failure" ]; then
+            echo "Code quality gate check failed. See step 'SonarQube Quality Gate Check'"
+          fi
+          exit 1
