refactor sonar config

diff --git a/.github/workflows/ci-backend.yml b/.github/workflows/ci-backend.yml
--- a/.github/workflows/ci-backend.yml
+++ b/.github/workflows/ci-backend.yml
@@ -28,7 +28,17 @@ jobs:
           cache: maven
 
       - name: Run tests & generate Jacoco report
+        id: run-backend-tests
         run: mvn clean verify jacoco:report
+        continue-on-error: true
+
+      - name: Verify coverage report existence and stop if missing
+        run: |
+          if [ ! -f "./target/site/jacoco/jacoco.xml" ]; then          
+           echo "Error: File 'back/target/site/jacoco/jacoco.xml' not found. Job failed."
+           exit 1
+          fi
+        shell: bash
 
       - name: Prepare directory for Pages
         working-directory: ${{ github.workspace }}
