Correct path coverage folder

diff --git a/.github/workflows/ci-frontend.yml b/.github/workflows/ci-frontend.yml
--- a/.github/workflows/ci-frontend.yml
+++ b/.github/workflows/ci-frontend.yml
@@ -38,8 +38,14 @@ jobs:
 
       - name: Verify front coverage report exists
         run: |
-          if [ ! -d "coverage" ] || [ ! -f "coverage/index.html" ]; then
-            echo "Error: Angular coverage report not found in front/coverage. Job failed."
+          if [ ! -d coverage ]; then
+            echo "Error: front/coverage directory not found."
+            exit 1
+          fi
+          # on récupère le premier dossier à l'intérieur de coverage
+          SUB=$(find coverage -maxdepth 1 -mindepth 1 -type d | head -n1)
+          if [ -z "$SUB" ] || [ ! -f "$SUB/index.html" ]; then
+            echo "Error: No index.html found in coverage subfolder."
             exit 1
           fi
         shell: bash
@@ -49,6 +55,7 @@ jobs:
         run: |
           rm -rf _site
           mkdir -p _site/coverage-frontend
+          COV_DIR=$(find front/coverage -maxdepth 1 -mindepth 1 -type d | head -n1)
           cp -R front/coverage/* _site/coverage-frontend/
           touch _site/.nojekyll
 
